[[Conclusions]]
== Conclusions

TBA

===  Future work

The following general recommendations for future innovation work items were made during the sprint:

* Themes, trees, nesting, and other strategies need to be explored. This is needed because data providers often have thousands of datasets that they need to manage or publish.
* There is a need for more experimentation on styles and coverages. Including how styles can be used to render/filter coverages.
* Tiled coverages and their support through OGC API - Coverages and OGC API - Tiles integration should be explored further.
* More experimentation is needed on workflows in relation to the OGC API - Processes - Part 3 : Workflows.
* Further development of the DGGS API, including work on client applications and visualization.
* There is a need to advance OGC APIs and other OGC standards to enable the cataloguing and discovery of models (e.g. AI/Machine Learning models). We need to explore how to sufficiently describe the models.
* The implications of OpenAPI 3.1, JSON Schema and Webhooks need to be examined and path towards transition identified.
* Some integration of the MapML format concept with the OGC API offerings, for example into the HTML representation of features, to enhance the spatial indexing of HTML.
* Enhancement of the Link Relations Register.

Standards Working Groups should consider introducing support for the following:

* Associations between records and other elements in catalogues
* Landing page of landing pages
* Searchable collections in OGC APIs (including the collections of collections)
