== About the February 2021 OGC API Sprint

The goal of the code sprint is to advance support of open geospatial standards within the developer community, whilst also advancing the standards themselves. Therefore, the code sprint will enable software developers to focus on projects that implement open geospatial standards for a period of three days. The code sprint will cover multiple ASF, OSGeo projects and OGC standards - including **OGC API** standards. All OGC, OSGeo and ASF projects and working groups are invited to participate. This Sprint is open to all participants, even if you are not active members or contributors to the efforts of the hosting organizations.

There will be an opportunity for joint discussion with other participants, as well as daily briefings from each project and working group. However, the majority of the time will be spent in collaboration between participants in active coding.

More information and a registration form for all of the sprints can be found at https://portal.ogc.org/public_ogc/register/20210217_code_sprint.php
