==== Code generation from OpenAPI definition documents

The sprint participants also discussed the ability of code generation tools to generate code that adequately describes the APIs defined using OpenAPI. Several participants commented that code generation tools seldom describe the business logic required to handle geospatial operations. Therefore, developers often have to manually write code into the stubs created by code generation tools. Further, the participants noted that for APIs that enable the publishing of dynamic resources at runtime, code generation tools often require additional manually written code to enable support of those dynamic resources. In this context, dynamic resource include feature collections that might chance their schema at some point in time. The participants therefore recommended that implementers of code generating tools should make enhancements to address some of those shortcomings, for example support for dynamic resources and enabling semantic awareness to provide context to API components.
