==== OGC API - Records

There was https://github.com/opengeospatial/joint-ogc-osgeo-asf-sprint-2021/issues/50[discussion] on how to represent the language for the record (possibly using an HTTP resource; the language that was requested). There was discussion on what happens if a client requests all the languages available at the same time. There is the potential to end up with verbose arrays. The participants suggested that a better approach could be to leverage hypermedia.

CubeWerx updated their server during the code sprint to follow the draft OGC API - Records specification. The team made https://www.pvretano.com/cubewerx/cubeserv/default/ogcapi/catalogues/collections/sentinel1cat/items[progress] on their implementation of support for OpenSearch. There was also discussion on potential integration with ActiveMQ to support implementation of a GSS.

The pygeoapi team advanced their implementation of OGC API - Records. There were some updates to the Records API schema. They also implemented itemType property to enable identification of the types of items returned by an API. The pygeoapi team also discussed with the GeoNode team about the possibility of using pygeoapi as a backend to GeoNode.

The pycsw team discussed how they are going to implement OGC API - Records, while still supporting versions 2 and 3 of the OGC Catalogue Services for the Web (CSW) standard. CSW is the predecessor of OGC API - Records. CSW supports the ability to publish and search collections of descriptive information (metadata) for data, services, and related information objects.
